### ISSUE TITLE
VecList::get and similar methods should take Index by reference?

### ISSUE THREAD

**Issue by nirvana-msu** [sgodwincs/dlv-list-rs#14]
## Motivations

I believe it would be better if [VecList::get](https://docs.rs/dlv-list/latest/dlv_list/struct.VecList.html#method.get) and similar methods borrowed `Index<T>` argument instead of taking ownership. Borrow seems sufficient (i.e. there is no advantage of taking ownership), and would make API more flexible.

My specific use-case if that I'm iterating over the linked list using [get_next_index](https://docs.rs/dlv-list/latest/dlv_list/struct.VecList.html#method.get_next_index), which gives me `Option<Index<T>>`. I need to use it in a few different parts of the code to get the item, however to do so more than once I have to clone the `Index`.

Moreover, even getting the next index requires taking ownership of existing index - so even if I only need to iterate through items in a simple sequential manner (using `get` and `get_next_index`), I still need to clone `Index`. Using iterator is not appropriate in my case as I need to modify collection while iterating (which is why I need the linked list in the first place).

P.S. As a side note, in order to obtain the very first index it seems I have to do `.indices().next()`, even though I don't really need an iterator. Would be nice if there was a shortcut to get that first index.

**Comment by sgodwincs** [comment]
I do recall going back and forth on whether to take ownership or take by reference. But the assumption was that indices should be small and it's simpler to take ownership. Is there a reason you can't make your type `T` copy?

**Comment by nirvana-msu** [comment]
Yeah that might be fine actually. Didn't realize just how small the `Index` is - passing by-copy probably makes sense.

Think we can close this. Thanks!
