### ISSUE TITLE
Remove dependency on `rand`

### ISSUE THREAD

**Issue by sgodwincs** [sgodwincs/dlv-list-rs#4]
rand is used to help reduce the chances that two maps may have the same generation (which would allow their indexes to be mixed up). This is extremely unlikely, but it's not foolproof. Besides, removing a dependency is always a good thing.

One approach I've seen used in a different data structure that used a generational index approach was to allocate a Arc<u8> and then use that pointer as a unique value since it'll be guaranteed by the allocator.

**Comment by kvark** [comment]
Latest dlv-list uses rand-0.7, while all the other crates moved to 0.8, so this is a bit of a problem now. Either publishing a patch that uses rand-0.8, or removing it altogether, would be great.

**Comment by sgodwincs** [comment]
I published 0.2.3 with the updated dependency. What is this crate used for that it causes a problem anyways?

**Comment by kvark** [comment]
Vange-rs depends on it transitively via rust-ini.
Thank you!

**Comment by kvark** [comment]
>    Updating dlv-list v0.2.2 -> v0.2.3
    Removing getrandom v0.1.16
    Removing rand v0.7.3
    Removing rand_chacha v0.2.2
    Removing rand_core v0.5.1
    Removing rand_hc v0.2.0
    Removing wasi v0.9.0+wasi-snapshot-preview1

**Comment by sgodwincs** [comment]
Removed in 0.2.4
