### ISSUE TITLE
Mobility within a list

### ISSUE THREAD

**Issue by yshui** [sgodwincs/dlv-list-rs#8]
## Motivations

Linked lists are capable of supporting moving a contiguous chunk of elements with O(1) time complexity. Currently this is not possible with `dlv_list`.

- Would you like to implement this feature? 
  y

## Solution

Add these functions:

```rust
/// Move the chunk from the `start` to `end` inclusive, to after the element at `after`
fn splice_after(&self, start: Index, end: Index, after: Index);
```

## Alternatives

N/A

## Additional context

Unsolved questions:

1. if `after` is between `start` and `end`, this function would end up creating 2 loops that won't be accessible from the head of the list. do we want to prevent this? this is not unsafe, and arguably isn't even a memory leak.

**Comment by yshui** [comment]
@sgodwincs i can't think of a way to disallow that without involving `O(n)` checks. maybe you would have a solution?

**Comment by sgodwincs** [comment]
Can you explain what the implementation of this looks like exactly? Ignoring the problem of loops etc., you are updating the link from `after` to point to `start` and vice versa. But what will you be updating the link from `end` to that wouldn't involve a scan? It also seems like this would always cause a branch in the list if `after` is not the last element.

**Comment by yshui** [comment]
so before the operation it's like:

`... -> start_prev -> start -> ... -> end -> end_next -> ... -> after -> after_next -> ...`

let `update_link(a, b)` be:

```
a.next = b;
b.prev = a;
```

we need to

```
update_link(start_prev, end_next);
update_link(after, start);
update_link(end, after_next);
```

**Comment by sgodwincs** [comment]
Ah OK, I misunderstood then. That makes sense to me. Regarding the looping problem, as long as it doesn't cause any other operation on the list to loop (e.g. iterators) and it's well documented, I think it's fine.
